AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cut_transcribe action group (MediaConvert cutter)

Parameters:
  VideoBucketName:     { Type: String }  # 예: video-input-pipeline-20250724
  MediaConvertRoleArn: { Type: String }  # 예: arn:aws:iam::<ACCOUNT_ID>:role/MediaConvertServiceRole

Resources:
  CutTranscribeLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: cuttranscribe.lambda_handler   # ← src/cut_transcribe.py
      Runtime: python3.12
      MemorySize: 1024
      Timeout: 900
      AutoPublishAlias: live
      Environment:
        Variables:
          VIDEO_BUCKET:           !Ref VideoBucketName
          MEDIACONVERT_ROLE_ARN:  !Ref MediaConvertRoleArn   # 코드에서 os.getenv로 읽도록 권장
      Policies:
        - Version: '2012-10-17'
          Statement:
            # S3 R/W
            - Sid: S3RWVideoBucket
              Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
                - s3:ListBucket
              Resource:
                - !Sub "arn:aws:s3:::${VideoBucketName}"
                - !Sub "arn:aws:s3:::${VideoBucketName}/*"

            # MediaConvert 잡
            - Sid: MediaConvertJobs
              Effect: Allow
              Action:
                - mediaconvert:CreateJob
                - mediaconvert:GetJob
                - mediaconvert:ListJobs
                - mediaconvert:DescribeEndpoints
              Resource: "*"

            # MediaConvert 서비스 역할 전달
            - Sid: PassMediaConvertRole
              Effect: Allow
              Action: iam:PassRole
              Resource: !Ref MediaConvertRoleArn

        - AWSLambdaBasicExecutionRole
  LambdaInvokeFromBedrock:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt CutTranscribeLambda.Arn
      Principal: bedrock.amazonaws.com

Outputs:
  CutTranscribeLambdaAliasArn:
    Value: !Sub '${CutTranscribeLambda.Arn}:live'

