AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: summary Agent (no alias)

Parameters:
  SummaryLambdaArn: { Type: String }
  AgentVersion:     { Type: String, Default: "DRAFT" }
  AgentModelId:     { Type: String, Default: "anthropic.claude-3-5-sonnet-20241022-v2:0" }

Resources:
  SummaryAgentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: bedrock.amazonaws.com }
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AgentFoundationModel
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: [ bedrock:InvokeModel, bedrock:InvokeModelWithResponseStream ]
                Resource: !Sub "arn:aws:bedrock:${AWS::Region}::foundation-model/${AgentModelId}"

  SummaryAgent:
    Type: AWS::Bedrock::Agent
    Properties:
      AgentName: !Sub "${AWS::StackName}-summary"
      AgentResourceRoleArn: !GetAtt SummaryAgentRole.Arn
      FoundationModel: !Ref AgentModelId
      AutoPrepare: true
      IdleSessionTTLInSeconds: 600
      Instruction: |
        # 영상 내용 요약 전문 에이전트
        당신은 영상의 음성 전사 데이터를 분석하여 내용을 요약하는 전문 AI입니다.
        ## 필수 동작
        1. **전사분석함수 호출**: 사용자 요청에 상관없이 반드시 먼저 전사분석함수를 호출하여 JSON 데이터 획득
        2. **요약 생성**: JSON 데이터의 transcript 내용을 분석하여 한국어로 요약 제공
        ## 출력 형식 (일반 텍스트)
        ## 영상 내용 요약
        전체 길이: [총 시간]분
        주요 내용:
        • [핵심 포인트 1]
        • [핵심 포인트 2]
        • [핵심 포인트 3]
        세부 내용:
        [시간대별 또는 주제별로 정리된 상세 내용]
        키워드: [주요 키워드들]
        ## 핵심 규칙
        - JSON이 아닌 자연스러운 한국어 텍스트로 응답
        - 전사 데이터의 시간 정보를 활용하여 구조적으로 정리
        - 중요한 내용과 맥락을 놓치지 않고 포함
        - 모든 응답은 한국어로만 작성

      ActionGroups:
        - ActionGroupName: summary_action_group
          ActionGroupExecutor:
            Lambda: !Ref SummaryLambdaArn
          ActionGroupState: ENABLED
          FunctionSchema:
            Functions:
              - Name: transcribe_analyze
                Description: 전사 JSON 획득
                Parameters: {}
                RequireConfirmation: DISABLED
              - Name: summarize_transcript
                Description: 전사 JSON 요약
                Parameters: {}
                RequireConfirmation: DISABLED

  AllowAgentInvokeSummary:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SummaryLambdaArn
      Action: lambda:InvokeFunction
      Principal: bedrock.amazonaws.com
      SourceArn: !GetAtt SummaryAgent.AgentArn

Outputs:
  SummaryAgentId:
    Value: !Ref SummaryAgent
  SummaryAgentArn:
    Value: !GetAtt SummaryAgent.AgentArn
