AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: transcribe Agent (no alias)

Parameters:
  TranscribeLambdaArn: { Type: String }
  AgentVersion:       { Type: String, Default: "DRAFT" }
  AgentModelId:       { Type: String, Default: "anthropic.claude-3-7-sonnet-20250219-v1:0" }

Resources:
  TranscribeAgentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: bedrock.amazonaws.com }
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AgentFoundationModel
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: [ bedrock:InvokeModel, bedrock:InvokeModelWithResponseStream ]
                Resource: !Sub "arn:aws:bedrock:${AWS::Region}::foundation-model/${AgentModelId}"

  TranscribeAgent:
    Type: AWS::Bedrock::Agent
    Properties:
      AgentName: !Sub "${AWS::StackName}-transcribe"
      AgentResourceRoleArn: !GetAtt TranscribeAgentRole.Arn
      FoundationModel: !Ref AgentModelId
      AutoPrepare: true
      IdleSessionTTLInSeconds: 600
      Instruction: |
        # 음성 전사 분석 AI 지침서 (Bedrock 분석용)
        **절대 규칙**: prompt 필드에는 반드시 사용자가 입력한 원본 질문을 **완전히 그대로** 넣어야 합니다. 검색 키워드가 아닙니다!

        ## 요청 유형 분류
        **1. 요약 요청 (직접 처리)**:
        - "내용 요약해줘", "요약해줘", "전체 내용 정리해줘" 등
        - **동작**: 전사분석함수 호출 → JSON 데이터 받기 → 직접 요약하여 일반 텍스트로 응답
        - **출력**: JSON 형식이 아닌 일반 한국어 텍스트로 요약 내용 제공

        **2. 검색 요청 (JSON 출력)**:
        - "[단어] 찾아줘", "[단어]라고 하는 장면", "[단어] 있어?" 등
        - **동작**: 전사분석함수 호출 → JSON 데이터 분석 → 검색 수행 → JSON 형식으로 응답

        ## 필수 동작
        1. **강제 함수 호출**: 사용자가 어떤 요청을 해도 **반드시 먼저** 전사분석함수를 호출하여 JSON 데이터 받기
           - 검색 요청: "[단어] 찾아줘", "[단어]라고 하는 장면", "[단어] 있어?" 등
           - 요약 요청: "내용 요약해줘", "요약해줘", "전체 내용 정리해줘" 등
           - **절대 "JSON 데이터가 없다"고 답변하지 말고 함수부터 호출**
        2. **요청 유형별 처리**:
           - **요약 요청**: JSON 데이터를 분석하여 일반 텍스트로 요약 제공
           - **검색 요청**: JSON 데이터를 직접 분석하여 검색 수행 후 JSON 형식으로 응답
        3. **한국어만 사용**: 모든 응답은 한국어로만 작성

        ## 요약 처리 방법
        **요약 요청 감지 키워드**:
        - "요약", "정리", "내용", "전체", "개요", "핵심" 등이 포함된 질문

        **요약 출력 형식**:
        ## 음성 전사 내용 요약
        **전체 길이**: [총 시간]
        **주요 내용**:
        - [핵심 내용 1]
        - [핵심 내용 2]
        - [핵심 내용 3]
        **세부 내용**:
        [시간대별 또는 주제별로 정리된 상세 내용]

        ## 검색어 추출 규칙
        (…중략… 네가 준 지침서 내용 그대로 계속…)

        ## 출력 형식
        ### 검색 요청 출력 (JSON 형식 필수)
        (발견시 / 여러 구간 / 미발견시 JSON 예시들 그대로…)

        ### 요약 요청 출력 (일반 텍스트)
        (설명 그대로…)

        ## 핵심 규칙
        - 검색 요청: **순수 JSON만 출력**, prompt는 사용자 입력 전체, 시간은 소수점 둘째자리, text는 순수 텍스트
        - 요약 요청: JSON 금지, 자연스러운 한국어 텍스트로 구조화 요약
        - 공통: 항상 먼저 전사분석함수 호출
      ActionGroups:
        - ActionGroupName: transcribe
          ActionGroupExecutor:
            Lambda: !Ref TranscribeLambdaArn
          ActionGroupState: ENABLED
          FunctionSchema:
            Functions:
              - Name: transcribe
                Description: 전사 JSON 조회/반환
                Parameters: {}
                RequireConfirmation: DISABLED

  AllowAgentInvokeTranscribe:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref TranscribeLambdaArn
      Action: lambda:InvokeFunction
      Principal: bedrock.amazonaws.com
      SourceArn: !GetAtt TranscribeAgent.AgentArn

Outputs:
  TranscribeAgentId:
    Value: !Ref TranscribeAgent
  TranscribeAgentArn:
    Value: !GetAtt TranscribeAgent.AgentArn
